// <auto-generated />
<<<<<<< HEAD
using FPT.DataAccess.Data;
=======
<<<<<<< HEAD
using FPT.DataAccess.Data;
=======
using FPT.DataAcess.Data;
>>>>>>> N-Tier-Architecture-02e
>>>>>>> dd438ed30c0d777fc96190ed8cbb0cd9517f75bd
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

<<<<<<< HEAD
namespace FPT.DataAccess.Migrations
=======
<<<<<<< HEAD
namespace FPT.DataAccess.Migrations
=======
namespace FPT.DataAcess.Migrations
>>>>>>> N-Tier-Architecture-02e
>>>>>>> dd438ed30c0d777fc96190ed8cbb0cd9517f75bd
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230716161747_AddCategoryTableToDb")]
    partial class AddCategoryTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FPTBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
